version: '{build}'
os: Visual Studio 2022
branches:
  only:
  - spanable
  - spanable-pre
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
skip_commits:
  files:
    - LICENSE
    - docs/*
    - '**/*.md'
install:
- git submodule update --init
- dotnet build -c Release src/SkyApm.Transport.Grpc.Protocol 
build_script:
- ps: ./scripts/build.ps1
artifacts:
- path: artifacts/packages/*.nupkg
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ihourglass/api/v2/package
  api_key:
    secure: Yk/Ur5r4zaTCJIEI1QQmgNul3you5LJaJGjF2wKlaua/zcItkAKHVHeYtZkcsla/
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
  on:
    branch: spanable
- provider: NuGet
  server: https://www.myget.org/F/ihourglass/api/v2/package
  api_key:
    secure: Yk/Ur5r4zaTCJIEI1QQmgNul3you5LJaJGjF2wKlaua/zcItkAKHVHeYtZkcsla/
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
  on:
    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: j/3BFKq4roi7zxB6W8ycAG784wwjQuYufYIx5InkExY78G8vkFRYLws+JaSbxrbg
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
  on:
    branch: spanable-pre
- provider: NuGet
  api_key:
    secure: j/3BFKq4roi7zxB6W8ycAG784wwjQuYufYIx5InkExY78G8vkFRYLws+JaSbxrbg
  skip_symbols: true
  artifact: /artifacts\/packages\/.+\.nupkg/
  on:
    appveyor_repo_tag: true
